lexer grammar MySqlLineageLexer;

SELECT: S E L E C T;
INSERT: I N S E R T;
REPLACE: R E P L A C E;
INTO: I N T O;
CREATE: C R E A T E;
TABLE: T A B L E;
VIEW: V I E W;
AS: A S;
FROM: F R O M;
JOIN: J O I N;
INNER: I N N E R;
LEFT: L E F T;
RIGHT: R I G H T;
FULL: F U L L;
CROSS: C R O S S;
OUTER: O U T E R;
ON: O N;
WHERE: W H E R E;
GROUP: G R O U P;
BY: B Y;
HAVING: H A V I N G;
ORDER: O R D E R;
LIMIT: L I M I T;
UNION: U N I O N;
ALL: A L L;
DISTINCT: D I S T I N C T;
UPDATE: U P D A T E;
SET: S E T;
DELETE: D E L E T E;
USING: U S I N G;
VALUES: V A L U E S;
DUPLICATE: D U P L I C A T E;
KEY: K E Y;

IDENTIFIER: [a-zA-Z_$\u0080-\uFFFF] [a-zA-Z0-9_$\u0080-\uFFFF]*;
BACKQUOTED_IDENTIFIER: '`' ('``' | ~'`')* '`';
STRING_LITERAL: '\'' ('\\' . | '\'\'' | ~['\\])* '\'';
DOUBLE_QUOTED_STRING: '"' ('\\' . | '""' | ~["\\])* '"';
NUMBER_LITERAL: [0-9]+ ('.' [0-9]+)?;

DOT: '.';
COMMA: ',';
SEMI: ';';
LPAREN: '(';
RPAREN: ')';
STAR: '*';
EQ: '=';
PLUS: '+';
MINUS: '-';
SLASH: '/';
PERCENT: '%';
LT: '<';
GT: '>';
BANG: '!';
QUESTION: '?';
COLON: ':';

LINE_COMMENT: ('--' ~[\r\n]* | '#' ~[\r\n]*) -> skip;
BLOCK_COMMENT: '/*' .*? '*/' -> skip;
WS: [ \t\r\n]+ -> skip;
OTHER: .;

fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];
