lexer grammar MySqlLineageLexer;

SELECT: S E L E C T;
WITH: W I T H;
INSERT: I N S E R T;
IGNORE: I G N O R E;
REPLACE: R E P L A C E;
INTO: I N T O;
CREATE: C R E A T E;
DROP: D R O P;
TRUNCATE: T R U N C A T E;
ALTER: A L T E R;
SHOW: S H O W;
DESCRIBE: D E S C R I B E;
DESC: D E S C;
COMMENT: C O M M E N T;
OR: O R;
AND: A N D;
NOT: N O T;
TEMPORARY: T E M P O R A R Y;
TABLE: T A B L E;
VIEW: V I E W;
IF: I F;
EXISTS: E X I S T S;
AS: A S;
LIKE: L I K E;
RENAME: R E N A M E;
TO: T O;
COLUMN: C O L U M N;
FROM: F R O M;
JOIN: J O I N;
INNER: I N N E R;
LEFT: L E F T;
RIGHT: R I G H T;
FULL: F U L L;
CROSS: C R O S S;
OUTER: O U T E R;
ON: O N;
USING: U S I N G;
WHERE: W H E R E;
GROUP: G R O U P;
BY: B Y;
HAVING: H A V I N G;
ORDER: O R D E R;
LIMIT: L I M I T;
OFFSET: O F F S E T;
UNION: U N I O N;
EXCEPT: E X C E P T;
INTERSECT: I N T E R S E C T;
ALL: A L L;
DISTINCT: D I S T I N C T;
UPDATE: U P D A T E;
SET: S E T;
DELETE: D E L E T E;
VALUES: V A L U E S;
DUPLICATE: D U P L I C A T E;
KEY: K E Y;
CASE: C A S E;
WHEN: W H E N;
THEN: T H E N;
ELSE: E L S E;
END: E N D;
CAST: C A S T;
IN: I N;
IS: I S;
BETWEEN: B E T W E E N;
NULL: N U L L;
TRUE: T R U E;
FALSE: F A L S E;
ASC: A S C;
OVER: O V E R;
PARTITION: P A R T I T I O N;
INTERVAL: I N T E R V A L;
LATERAL: L A T E R A L;
DEFAULT: D E F A U L T;
ADD: A D D;
EXTERNAL: E X T E R N A L;
ENGINE: E N G I N E;
CHARSET: C H A R S E T;
CHARACTER: C H A R A C T E R;
COLLATE: C O L L A T E;
AUTO_INCREMENT: A U T O '_'? I N C R E M E N T;

IDENTIFIER: [a-zA-Z_$-￿] [a-zA-Z0-9_$-￿]*;
BACKQUOTED_IDENTIFIER: '`' ('``' | ~'`')* '`';
STRING_LITERAL: '\'' ('\\' . | '\'\'' | ~['\\])* '\'';
DOUBLE_QUOTED_STRING: '"' ('\\' . | '""' | ~["\\])* '"';
NUMBER_LITERAL: [0-9]+ ('.' [0-9]+)?;

DOT: '.';
COMMA: ',';
SEMI: ';';
LPAREN: '(';
RPAREN: ')';
STAR: '*';
EQ: '=';
NEQ: '!=' | '<>';
LTE: '<=';
GTE: '>=';
LT: '<';
GT: '>';
PLUS: '+';
MINUS: '-';
SLASH: '/';
PERCENT: '%';
CONCAT: '||';
BANG: '!';
QUESTION: '?';
COLON: ':';

LINE_COMMENT: ('--' ~[\r\n]* | '#' ~[\r\n]*) -> skip;
BLOCK_COMMENT: '/*' .*? '*/' -> skip;
WS: [ \t\r\n]+ -> skip;
OTHER: .;

fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];
