lexer grammar PostgreSqlLineageLexer;

SELECT: S E L E C T;
WITH: W I T H;
INSERT: I N S E R T;
REPLACE: R E P L A C E;
INTO: I N T O;
MERGE: M E R G E;
MATCHED: M A T C H E D;
CREATE: C R E A T E;
DROP: D R O P;
TRUNCATE: T R U N C A T E;
ALTER: A L T E R;
TYPE: T Y P E;
ENUM: E N U M;
SHOW: S H O W;
DESCRIBE: D E S C R I B E;
DESC: D E S C;
COMMENT: C O M M E N T;
COPY: C O P Y;
VACUUM: V A C U U M;
ANALYZE: A N A L Y Z E;
REINDEX: R E I N D E X;
GRANT: G R A N T;
REVOKE: R E V O K E;
BEFORE: B E F O R E;
AFTER: A F T E R;
EXTENSION: E X T E N S I O N;
SCHEMA: S C H E M A;
FUNCTION: F U N C T I O N;
PROCEDURE: P R O C E D U R E;
SEQUENCE: S E Q U E N C E;
POLICY: P O L I C Y;
PERMISSIVE: P E R M I S S I V E;
RESTRICTIVE: R E S T R I C T I V E;
PUBLICATION: P U B L I C A T I O N;
SUBSCRIPTION: S U B S C R I P T I O N;
CONNECTION: C O N N E C T I O N;
RETURNS: R E T U R N S;
LANGUAGE: L A N G U A G E;
SEARCH_PATH: S E A R C H '_'? P A T H;
MATERIALIZED: M A T E R I A L I Z E D;
DATA: D A T A;
NO: N O;
REFRESH: R E F R E S H;
CONCURRENTLY: C O N C U R R E N T L Y;
INCLUDING: I N C L U D I N G;
INCLUDE: I N C L U D E;
EXCLUDING: E X C L U D I N G;
VERBOSE: V E R B O S E;
FREEZE: F R E E Z E;
FULL: F U L L;
STDIN: S T D I N;
STDOUT: S T D O U T;
PROGRAM: P R O G R A M;
FORMAT: F O R M A T;
CSV: C S V;
HEADER: H E A D E R;
DELIMITER: D E L I M I T E R;
OR: O R;
AND: A N D;
NOT: N O T;
TEMPORARY: T E M P O R A R Y;
UNLOGGED: U N L O G G E D;
TABLE: T A B L E;
TABLES: T A B L E S;
VIEW: V I E W;
IF: I F;
EXISTS: E X I S T S;
AS: A S;
LIKE: L I K E;
ILIKE: I L I K E;
RENAME: R E N A M E;
TO: T O;
COLUMN: C O L U M N;
CHECK: C H E C K;
FROM: F R O M;
JOIN: J O I N;
INNER: I N N E R;
LEFT: L E F T;
RIGHT: R I G H T;
CROSS: C R O S S;
OUTER: O U T E R;
ON: O N;
USING: U S I N G;
WHERE: W H E R E;
GROUP: G R O U P;
BY: B Y;
HAVING: H A V I N G;
ORDER: O R D E R;
LIMIT: L I M I T;
OFFSET: O F F S E T;
UNION: U N I O N;
EXCEPT: E X C E P T;
INTERSECT: I N T E R S E C T;
ALL: A L L;
DISTINCT: D I S T I N C T;
UPDATE: U P D A T E;
SET: S E T;
BEGIN: B E G I N;
START: S T A R T;
TRANSACTION: T R A N S A C T I O N;
COMMIT: C O M M I T;
ROLLBACK: R O L L B A C K;
SAVEPOINT: S A V E P O I N T;
RELEASE: R E L E A S E;
WORK: W O R K;
ISOLATION: I S O L A T I O N;
LEVEL: L E V E L;
READ: R E A D;
WRITE: W R I T E;
REPEATABLE: R E P E A T A B L E;
COMMITTED: C O M M I T T E D;
UNCOMMITTED: U N C O M M I T T E D;
SERIALIZABLE: S E R I A L I Z A B L E;
SYSTEM: S Y S T E M;
USER: U S E R;
DELETE: D E L E T E;
VALUE: V A L U E;
VALUES: V A L U E S;
CONFLICT: C O N F L I C T;
DO: D O;
NOTHING: N O T H I N G;
RETURNING: R E T U R N I N G;
OVERRIDING: O V E R R I D I N G;
KEY: K E Y;
PRIMARY: P R I M A R Y;
UNIQUE: U N I Q U E;
INDEX: I N D E X;
CONSTRAINT: C O N S T R A I N T;
CASE: C A S E;
WHEN: W H E N;
THEN: T H E N;
ELSE: E L S E;
END: E N D;
CAST: C A S T;
IN: I N;
IS: I S;
BETWEEN: B E T W E E N;
NULL: N U L L;
TRUE: T R U E;
FALSE: F A L S E;
ASC: A S C;
OVER: O V E R;
PARTITION: P A R T I T I O N;
OF: O F;
FOR: F O R;
INTERVAL: I N T E R V A L;
LATERAL: L A T E R A L;
DEFAULT: D E F A U L T;
SEPARATOR: S E P A R A T O R;
FILTER: F I L T E R;
WITHIN: W I T H I N;
RECURSIVE: R E C U R S I V E;
ONLY: O N L Y;
INHERITS: I N H E R I T S;
NULLS: N U L L S;
FIRST: F I R S T;
LAST: L A S T;
ROWS: R O W S;
RANGE: R A N G E;
GROUPS: G R O U P S;
ROW: R O W;
CURRENT: C U R R E N T;
UNBOUNDED: U N B O U N D E D;
PRECEDING: P R E C E D I N G;
FOLLOWING: F O L L O W I N G;
ADD: A D D;
EXTERNAL: E X T E R N A L;
ENGINE: E N G I N E;
CHARSET: C H A R S E T;
CHARACTER: C H A R A C T E R;
COLLATE: C O L L A T E;
AUTO_INCREMENT: A U T O '_'? I N C R E M E N T;
CASCADE: C A S C A D E;
RESTRICT: R E S T R I C T;
ATTACH: A T T A C H;
DETACH: D E T A C H;

IDENTIFIER: [a-zA-Z_$-￿] [a-zA-Z0-9_$-￿]*;
BACKQUOTED_IDENTIFIER: '`' ('``' | ~'`')* '`';
STRING_LITERAL: '\'' ('\\' . | '\'\'' | ~['\\])* '\'';
DOUBLE_QUOTED_STRING: '"' ('\\' . | '""' | ~["\\])* '"';
NUMBER_LITERAL: [0-9]+ ('.' [0-9]+)?;

DOT: '.';
COMMA: ',';
SEMI: ';';
LPAREN: '(';
RPAREN: ')';
STAR: '*';
EQ: '=';
NEQ: '!=' | '<>';
LTE: '<=';
GTE: '>=';
LT: '<';
GT: '>';
PLUS: '+';
MINUS: '-';
SLASH: '/';
PERCENT: '%';
CONCAT: '||';
ARROW: '->';
ARROW_TEXT: '->>';
HASH_ARROW: '#>';
HASH_ARROW_TEXT: '#>>';
CONTAINS: '@>';
CONTAINED_BY: '<@';
QUESTION_PIPE: '?|';
QUESTION_AMP: '?&';
BANG: '!';
QUESTION: '?';
COLON: ':';
LBRACKET: '[';
RBRACKET: ']';

LINE_COMMENT: ('--' ~[\r\n]* | '#' ~[\r\n]*) -> skip;
BLOCK_COMMENT: '/*' .*? '*/' -> skip;
WS: [ \t\r\n]+ -> skip;
OTHER: .;

fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];
