lexer grammar OracleLineageLexer;

SELECT: S E L E C T;
WITH: W I T H;
INSERT: I N S E R T;
INTO: I N T O;
MERGE: M E R G E;
MATCHED: M A T C H E D;
CREATE: C R E A T E;
DROP: D R O P;
TRUNCATE: T R U N C A T E;
ALTER: A L T E R;
SHOW: S H O W;
DESCRIBE: D E S C R I B E;
DESC: D E S C;
COMMENT: C O M M E N T;
MATERIALIZED: M A T E R I A L I Z E D;
UNIQUE: U N I Q U E;
BITMAP: B I T M A P;
INDEX: I N D E X;
FUNCTION: F U N C T I O N;
PROCEDURE: P R O C E D U R E;
SESSION: S E S S I O N;
PRIMARY: P R I M A R Y;
KEY: K E Y;
ANALYZE: A N A L Y Z E;
COMPUTE: C O M P U T E;
ESTIMATE: E S T I M A T E;
STATISTICS: S T A T I S T I C S;
VALIDATE: V A L I D A T E;
STRUCTURE: S T R U C T U R E;
OR: O R;
AND: A N D;
NOT: N O T;
TEMPORARY: T E M P O R A R Y;
TABLE: T A B L E;
VIEW: V I E W;
IF: I F;
EXISTS: E X I S T S;
AS: A S;
LIKE: L I K E;
RENAME: R E N A M E;
TO: T O;
COLUMN: C O L U M N;
FROM: F R O M;
JOIN: J O I N;
INNER: I N N E R;
LEFT: L E F T;
RIGHT: R I G H T;
FULL: F U L L;
CROSS: C R O S S;
OUTER: O U T E R;
ON: O N;
USING: U S I N G;
WHERE: W H E R E;
GROUP: G R O U P;
BY: B Y;
HAVING: H A V I N G;
ORDER: O R D E R;
LIMIT: L I M I T;
OFFSET: O F F S E T;
UNION: U N I O N;
EXCEPT: E X C E P T;
INTERSECT: I N T E R S E C T;
ALL: A L L;
FIRST: F I R S T;
NEXT: N E X T;
FETCH: F E T C H;
ROW: R O W;
ROWS: R O W S;
ONLY: O N L Y;
DISTINCT: D I S T I N C T;
UPDATE: U P D A T E;
SET: S E T;
DELETE: D E L E T E;
OVERWRITE: O V E R W R I T E;
VALUES: V A L U E S;
CASE: C A S E;
WHEN: W H E N;
THEN: T H E N;
ELSE: E L S E;
END: E N D;
CAST: C A S T;
IN: I N;
IS: I S;
BETWEEN: B E T W E E N;
NULL: N U L L;
TRUE: T R U E;
FALSE: F A L S E;
ASC: A S C;
OVER: O V E R;
PARTITION: P A R T I T I O N;
INTERVAL: I N T E R V A L;
DEFAULT: D E F A U L T;
ADD: A D D;
EXTERNAL: E X T E R N A L;
START: S T A R T;
CONNECT: C O N N E C T;
PRIOR: P R I O R;
DUAL: D U A L;
REPLACE: R E P L A C E;
STORED: S T O R E D;
FORMAT: F O R M A T;

IDENTIFIER: [a-zA-Z_$-￿] [a-zA-Z0-9_$-￿]*;
BACKQUOTED_IDENTIFIER: '"' ('""' | ~'"')* '"';
STRING_LITERAL: '\'' ('\\' . | '\'\'' | ~['\\])* '\'';
DOUBLE_QUOTED_STRING: '"' ('\\' . | '""' | ~["\\])* '"';
NUMBER_LITERAL: [0-9]+ ('.' [0-9]+)?;

DOT: '.';
COMMA: ',';
SEMI: ';';
LPAREN: '(';
RPAREN: ')';
STAR: '*';
EQ: '=';
NEQ: '!=' | '<>';
LTE: '<=';
GTE: '>=';
LT: '<';
GT: '>';
PLUS: '+';
MINUS: '-';
SLASH: '/';
PERCENT: '%';
CONCAT: '||';
BANG: '!';
QUESTION: '?';
COLON: ':';

LINE_COMMENT: '--' ~[\r\n]* -> skip;
BLOCK_COMMENT: '/*' .*? '*/' -> skip;
WS: [ \t\r\n]+ -> skip;
OTHER: .;

fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];
