lexer grammar SqlServerLineageLexer;

SELECT: S E L E C T;
TOP: T O P;
WITH: W I T H;
WITHIN: W I T H I N;
INSERT: I N S E R T;
UPDATE: U P D A T E;
DELETE: D E L E T E;
MERGE: M E R G E;
MATCHED: M A T C H E D;
SOURCE: S O U R C E;
TARGET: T A R G E T;
INTO: I N T O;
CREATE: C R E A T E;
DROP: D R O P;
TRUNCATE: T R U N C A T E;
ALTER: A L T E R;
GRANT: G R A N T;
REVOKE: R E V O K E;
SHOW: S H O W;
DESCRIBE: D E S C R I B E;
DESC: D E S C;
COMMENT: C O M M E N T;
CONTAINED: C O N T A I N E D;
DECLARE: D E C L A R E;
BEGIN: B E G I N;
COMMIT: C O M M I T;
ROLLBACK: R O L L B A C K;
SAVE: S A V E;
TRAN: T R A N;
TRANSACTION: T R A N S A C T I O N;
TRANSFER: T R A N S F E R;
SCHEMA: S C H E M A;
PROCEDURE: P R O C E D U R E;
FUNCTION: F U N C T I O N;
SYNONYM: S Y N O N Y M;
TRIGGER: T R I G G E R;
SYSTEM_TIME: S Y S T E M '_' T I M E;
USE: U S E;
BACKUP: B A C K U P;
RESTORE: R E S T O R E;
DATABASE: D A T A B A S E;
LOG: L O G;
DISK: D I S K;
DBCC: D B C C;
CHECKDB: C H E C K D B;
CHECKTABLE: C H E C K T A B L E;
STATISTICS: S T A T I S T I C S;
OFF: O F F;
OR: O R;
AND: A N D;
NOT: N O T;
TEMPORARY: T E M P O R A R Y;
TABLE: T A B L E;
VIEW: V I E W;
TYPE: T Y P E;
IF: I F;
EXISTS: E X I S T S;
EXEC: E X E C;
EXECUTE: E X E C U T E;
AS: A S;
AFTER: A F T E R;
LIKE: L I K E;
RENAME: R E N A M E;
TO: T O;
COLUMN: C O L U M N;
SET: S E T;
FROM: F R O M;
USING: U S I N G;
JOIN: J O I N;
INNER: I N N E R;
LEFT: L E F T;
RIGHT: R I G H T;
FULL: F U L L;
CROSS: C R O S S;
APPLY: A P P L Y;
OUTER: O U T E R;
ON: O N;
WHERE: W H E R E;
GROUP: G R O U P;
GROUPING: G R O U P I N G;
SETS: S E T S;
BY: B Y;
HAVING: H A V I N G;
ORDER: O R D E R;
LIMIT: L I M I T;
OFFSET: O F F S E T;
OF: O F;
FETCH: F E T C H;
FIRST: F I R S T;
NEXT: N E X T;
ROW: R O W;
ROWS: R O W S;
ROLLUP: R O L L U P;
CUBE: C U B E;
ONLY: O N L Y;
PERCENT_KEYWORD: P E R C E N T;
TIES: T I E S;
UNION: U N I O N;
EXCEPT: E X C E P T;
INTERSECT: I N T E R S E C T;
ALL: A L L;
DISTINCT: D I S T I N C T;
PARTITION: P A R T I T I O N;
PARTITIONS: P A R T I T I O N S;
PIVOT: P I V O T;
UNPIVOT: U N P I V O T;
VALUES: V A L U E S;
CASE: C A S E;
WHEN: W H E N;
THEN: T H E N;
ELSE: E L S E;
END: E N D;
CAST: C A S T;
COLLATE: C O L L A T E;
IN: I N;
FOR: F O R;
IS: I S;
BETWEEN: B E T W E E N;
NULL: N U L L;
TRUE: T R U E;
FALSE: F A L S E;
ASC: A S C;
OVER: O V E R;
INTERVAL: I N T E R V A L;
DEFAULT: D E F A U L T;
ADD: A D D;
EXTERNAL: E X T E R N A L;
IDENTITY: I D E N T I T Y;
OUTPUT: O U T P U T;
OBJECT: O B J E C T;
JSON: J S O N;
XML: X M L;
ROOT: R O O T;
NOLOCK: N O L O C K;
OPTION: O P T I O N;
RECOMPILE: R E C O M P I L E;
MAXDOP: M A X D O P;
OPTIMIZE: O P T I M I Z E;
TRY: T R Y;
CATCH: C A T C H;
PRINT: P R I N T;
THROW: T H R O W;
RAISERROR: R A I S E R R O R;
RETURN: R E T U R N;
TRY_CAST: T R Y '_' C A S T;
CONVERT: C O N V E R T;
TRY_CONVERT: T R Y '_' C O N V E R T;
REPLACE: R E P L A C E;
UNIQUE: U N I Q U E;
PRIMARY: P R I M A R Y;
KEY: K E Y;
INDEX: I N D E X;
INCLUDE: I N C L U D E;
CLUSTERED: C L U S T E R E D;
NONCLUSTERED: N O N C L U S T E R E D;
REBUILD: R E B U I L D;
REORGANIZE: R E O R G A N I Z E;
DISABLE: D I S A B L E;
PERSISTED: P E R S I S T E D;

VARIABLE_IDENTIFIER: '@'[a-zA-Z_$-￿] [a-zA-Z0-9_$-￿]*;
IDENTIFIER: '#'? '#'?[a-zA-Z_$-￿] [a-zA-Z0-9_$-￿]*;
BACKQUOTED_IDENTIFIER: '[' (']]' | ~']')* ']';
STRING_LITERAL: '\'' ('\\' . | '\'\'' | ~['\\])* '\'';
DOUBLE_QUOTED_STRING: '"' ('\\' . | '""' | ~["\\])* '"';
NUMBER_LITERAL: [0-9]+ ('.' [0-9]+)?;

DOT: '.';
COMMA: ',';
SEMI: ';';
LPAREN: '(';
RPAREN: ')';
STAR: '*';
EQ: '=';
NEQ: '!=' | '<>';
LTE: '<=';
GTE: '>=';
LT: '<';
GT: '>';
PLUS: '+';
MINUS: '-';
SLASH: '/';
PERCENT: '%';
CONCAT: '||';
BANG: '!';
QUESTION: '?';
DOUBLE_COLON: '::';
COLON: ':';

LINE_COMMENT: '--' ~[\r\n]* -> skip;
BLOCK_COMMENT: '/*' .*? '*/' -> skip;
WS: [ \t\r\n]+ -> skip;
OTHER: .;

fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];
