lexer grammar HiveLineageLexer;

SELECT: S E L E C T;
WITH: W I T H;
INSERT: I N S E R T;
UPDATE: U P D A T E;
DELETE: D E L E T E;
OVERWRITE: O V E R W R I T E;
INTO: I N T O;
DIRECTORY: D I R E C T O R Y;
CREATE: C R E A T E;
DROP: D R O P;
TRUNCATE: T R U N C A T E;
ALTER: A L T E R;
USE: U S E;
SHOW: S H O W;
DESCRIBE: D E S C R I B E;
COMMENT: C O M M E N T;
EXTERNAL: E X T E R N A L;
TEMPORARY: T E M P O R A R Y;
TABLE: T A B L E;
VIEW: V I E W;
IF: I F;
NOT: N O T;
EXISTS: E X I S T S;
AS: A S;
LIKE: L I K E;
RENAME: R E N A M E;
TO: T O;
COLUMN: C O L U M N;
SET: S E T;
FROM: F R O M;
USING: U S I N G;
JOIN: J O I N;
INNER: I N N E R;
LEFT: L E F T;
RIGHT: R I G H T;
FULL: F U L L;
CROSS: C R O S S;
OUTER: O U T E R;
ON: O N;
WHERE: W H E R E;
GROUP: G R O U P;
BY: B Y;
HAVING: H A V I N G;
ORDER: O R D E R;
SORT: S O R T;
DISTRIBUTE: D I S T R I B U T E;
CLUSTER: C L U S T E R;
LIMIT: L I M I T;
UNION: U N I O N;
ALL: A L L;
DISTINCT: D I S T I N C T;
PARTITION: P A R T I T I O N;
STORED: S T O R E D;
ROW: R O W;
FORMAT: F O R M A T;
DELIMITED: D E L I M I T E D;
FIELDS: F I E L D S;
TERMINATED: T E R M I N A T E D;
COLLECTION: C O L L E C T I O N;
ITEMS: I T E M S;
MAP: M A P;
KEYS: K E Y S;
LINES: L I N E S;
INPUTFORMAT: I N P U T F O R M A T;
OUTPUTFORMAT: O U T P U T F O R M A T;

// Additional keywords for full parser
AND: A N D;
OR: O R;
CASE: C A S E;
WHEN: W H E N;
THEN: T H E N;
ELSE: E L S E;
END: E N D;
CAST: C A S T;
VALUES: V A L U E S;
BETWEEN: B E T W E E N;
IN: I N;
IS: I S;
NULL: N U L L;
TRUE: T R U E;
FALSE: F A L S E;
ASC: A S C;
DESC: D E S C;
OFFSET: O F F S E T;
EXCEPT: E X C E P T;
INTERSECT: I N T E R S E C T;
OVER: O V E R;
INTERVAL: I N T E R V A L;
LATERAL: L A T E R A L;
DEFAULT: D E F A U L T;
ADD: A D D;
REPLACE: R E P L A C E;

// Hive-specific keywords
LOAD: L O A D;
DATA: D A T A;
INPATH: I N P A T H;
EXPORT: E X P O R T;
IMPORT: I M P O R T;
LOCAL: L O C A L;
LOCATION: L O C A T I O N;
TBLPROPERTIES: T B L P R O P E R T I E S;
SERDEPROPERTIES: S E R D E P R O P E R T I E S;
COLUMNS: C O L U M N S;
PARTITIONED: P A R T I T I O N E D;
PARTITIONS: P A R T I T I O N S;
DATABASE: D A T A B A S E;
DATABASES: D A T A B A S E S;
SCHEMA: S C H E M A;
SCHEMAS: S C H E M A S;
MSCK: M S C K;
REPAIR: R E P A I R;
ANALYZE: A N A L Y Z E;
COMPUTE: C O M P U T E;
STATISTICS: S T A T I S T I C S;
NOSCAN: N O S C A N;
CASCADE: C A S C A D E;
RESTRICT: R E S T R I C T;
PURGE: P U R G E;
SYNC: S Y N C;

IDENTIFIER: [a-zA-Z_$-￿] [a-zA-Z0-9_$-￿]*;
BACKQUOTED_IDENTIFIER: '`' ('``' | ~'`')* '`';
STRING_LITERAL: '\'' ('\\' . | '\'\'' | ~['\\])* '\'';
DOUBLE_QUOTED_STRING: '"' ('\\' . | '""' | ~["\\])* '"';
NUMBER_LITERAL: [0-9]+ ('.' [0-9]+)?;

DOT: '.';
COMMA: ',';
SEMI: ';';
LPAREN: '(';
RPAREN: ')';
STAR: '*';
EQ: '=';
NEQ: '!=' | '<>';
LTE: '<=';
GTE: '>=';
LT: '<';
GT: '>';
PLUS: '+';
MINUS: '-';
SLASH: '/';
PERCENT: '%';
CONCAT: '||';
BANG: '!';
QUESTION: '?';
COLON: ':';

LINE_COMMENT: ('--' ~[\r\n]* | '#' ~[\r\n]*) -> skip;
BLOCK_COMMENT: '/*' .*? '*/' -> skip;
WS: [ \t\r\n]+ -> skip;
OTHER: .;

fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];
