lexer grammar FlinkLineageLexer;

SELECT: S E L E C T;
WITH: W I T H;
INSERT: I N S E R T;
INTO: I N T O;
CREATE: C R E A T E;
DROP: D R O P;
TRUNCATE: T R U N C A T E;
ALTER: A L T E R;
USE: U S E;
SHOW: S H O W;
DESCRIBE: D E S C R I B E;
DESC: D E S C;
COMMENT: C O M M E N T;
EXPLAIN: E X P L A I N;
ANALYZE: A N A L Y Z E;
LOAD: L O A D;
UNLOAD: U N L O A D;
REMOVE: R E M O V E;
UNNEST: U N N E S T;
OR: O R;
AND: A N D;
NOT: N O T;
TEMPORARY: T E M P O R A R Y;
TABLE: T A B L E;
TABLES: T A B L E S;
VIEW: V I E W;
VIEWS: V I E W S;
CATALOG: C A T A L O G;
CATALOGS: C A T A L O G S;
DATABASE: D A T A B A S E;
DATABASES: D A T A B A S E S;
FUNCTION: F U N C T I O N;
FUNCTIONS: F U N C T I O N S;
MODEL: M O D E L;
MATERIALIZED: M A T E R I A L I Z E D;
MODULE: M O D U L E;
MODULES: M O D U L E S;
JAR: J A R;
JARS: J A R S;
ARTIFACT: A R T I F A C T;
MATCH_RECOGNIZE: M A T C H '_' R E C O G N I Z E;
MEASURES: M E A S U R E S;
PATTERN: P A T T E R N;
DEFINE: D E F I N E;
ONE: O N E;
PER: P E R;
MATCH: M A T C H;
SKIP_KEYWORD: S K I P;
PAST: P A S T;
LAST: L A S T;
FRESHNESS: F R E S H N E S S;
REFRESH_MODE: R E F R E S H '_' M O D E;
CONTINUOUS: C O N T I N U O U S;
REFRESH: R E F R E S H;
SUSPEND: S U S P E N D;
RESUME: R E S U M E;
IF: I F;
EXISTS: E X I S T S;
AS: A S;
LIKE: L I K E;
RENAME: R E N A M E;
TO: T O;
COLUMN: C O L U M N;
CONSTRAINT: C O N S T R A I N T;
METADATA: M E T A D A T A;
VIRTUAL: V I R T U A L;
FROM: F R O M;
JOIN: J O I N;
INNER: I N N E R;
LEFT: L E F T;
RIGHT: R I G H T;
FULL: F U L L;
CROSS: C R O S S;
OUTER: O U T E R;
ON: O N;
USING: U S I N G;
WHERE: W H E R E;
GROUP: G R O U P;
BY: B Y;
ROLLUP: R O L L U P;
CUBE: C U B E;
GROUPING: G R O U P I N G;
SETS: S E T S;
HAVING: H A V I N G;
WINDOW: W I N D O W;
ORDER: O R D E R;
LIMIT: L I M I T;
OFFSET: O F F S E T;
FETCH: F E T C H;
NEXT: N E X T;
ONLY: O N L Y;
UNION: U N I O N;
EXCEPT: E X C E P T;
INTERSECT: I N T E R S E C T;
ALL: A L L;
ANY: A N Y;
SOME: S O M E;
DISTINCT: D I S T I N C T;
UPDATE: U P D A T E;
SET: S E T;
DELETE: D E L E T E;
OVERWRITE: O V E R W R I T E;
VALUES: V A L U E S;
CASE: C A S E;
WHEN: W H E N;
THEN: T H E N;
ELSE: E L S E;
END: E N D;
CAST: C A S T;
IN: I N;
IS: I S;
BETWEEN: B E T W E E N;
NULL: N U L L;
TRUE: T R U E;
FALSE: F A L S E;
UNKNOWN: U N K N O W N;
ASC: A S C;
OVER: O V E R;
FILTER: F I L T E R;
PARTITION: P A R T I T I O N;
PARTITIONED: P A R T I T I O N E D;
SYS: S Y S;
SYSTEM: S Y S T E M;
INTERVAL: I N T E R V A L;
SECOND: S E C O N D;
MINUTE: M I N U T E;
HOUR: H O U R;
DAY: D A Y;
LATERAL: L A T E R A L;
DEFAULT: D E F A U L T;
ADD: A D D;
FIRST: F I R S T;
AFTER: A F T E R;
REPLACE: R E P L A C E;
RESET: R E S E T;
EXTERNAL: E X T E R N A L;
ROW: R O W;
FORMAT: F O R M A T;
STORED: S T O R E D;
WATERMARK: W A T E R M A R K;
CONNECTOR: C O N N E C T O R;
DISTRIBUTED: D I S T R I B U T E D;
DISTRIBUTION: D I S T R I B U T I O N;
HASH: H A S H;
BUCKET: B U C K E T;
BUCKETS: B U C K E T S;
INCLUDING: I N C L U D I N G;
EXCLUDING: E X C L U D I N G;
OVERWRITING: O V E R W R I T I N G;
OPTIONS: O P T I O N S;
GENERATED: G E N E R A T E D;
ALWAYS: A L W A Y S;
EXECUTE: E X E C U T E;
STATEMENT: S T A T E M E N T;
BEGIN: B E G I N;
LANGUAGE: L A N G U A G E;
JAVA: J A V A;
SCALA: S C A L A;
PYTHON: P Y T H O N;
CASCADE: C A S C A D E;
RESTRICT: R E S T R I C T;
SYSTEM_TIME: S Y S T E M '_' T I M E;
PERIOD: P E R I O D;
FOR: F O R;
PRIMARY: P R I M A R Y;
KEY: K E Y;
ENFORCED: E N F O R C E D;

// Window frame
ROWS: R O W S;
RANGE: R A N G E;
UNBOUNDED: U N B O U N D E D;
PRECEDING: P R E C E D I N G;
FOLLOWING: F O L L O W I N G;
CURRENT: C U R R E N T;

// Temporal join
OF: O F;

// TVF windowing
TUMBLE: T U M B L E;
HOP: H O P;
SESSION: S E S S I O N;
CUMULATE: C U M U L A T E;
DESCRIPTOR: D E S C R I P T O R;

// MERGE
MERGE: M E R G E;
MATCHED: M A T C H E D;

IDENTIFIER: [a-zA-Z_$-￿] [a-zA-Z0-9_$-￿]*;
BACKQUOTED_IDENTIFIER: '`' ('``' | ~'`')* '`';
STRING_LITERAL: '\'' ('\\' . | '\'\'' | ~['\\])* '\'';
DOUBLE_QUOTED_STRING: '"' ('\\' . | '""' | ~["\\])* '"';
NUMBER_LITERAL: [0-9]+ ('.' [0-9]+)?;

DOT: '.';
COMMA: ',';
SEMI: ';';
LPAREN: '(';
RPAREN: ')';
STAR: '*';
EQ: '=';
NEQ: '!=' | '<>';
LTE: '<=';
GTE: '>=';
LT: '<';
GT: '>';
PLUS: '+';
MINUS: '-';
SLASH: '/';
PERCENT: '%';
CONCAT: '||';
BANG: '!';
QUESTION: '?';
COLON: ':';

LINE_COMMENT: '--' ~[\r\n]* -> skip;
BLOCK_COMMENT: '/*' .*? '*/' -> skip;
WS: [ \t\r\n]+ -> skip;
OTHER: .;

fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];
