lexer grammar StarRocksLineageLexer;

SELECT: S E L E C T;
WITH: W I T H;
INSERT: I N S E R T;
UPDATE: U P D A T E;
DELETE: D E L E T E;
OVERWRITE: O V E R W R I T E;
INTO: I N T O;
CREATE: C R E A T E;
MATERIALIZED: M A T E R I A L I Z E D;
DROP: D R O P;
TRUNCATE: T R U N C A T E;
ALTER: A L T E R;
SHOW: S H O W;
DESCRIBE: D E S C R I B E;
COMMENT: C O M M E N T;
EXTERNAL: E X T E R N A L;
TEMPORARY: T E M P O R A R Y;
TABLE: T A B L E;
VIEW: V I E W;
IF: I F;
NOT: N O T;
EXISTS: E X I S T S;
AS: A S;
LIKE: L I K E;
RENAME: R E N A M E;
TO: T O;
COLUMN: C O L U M N;
SET: S E T;
FROM: F R O M;
USING: U S I N G;
JOIN: J O I N;
INNER: I N N E R;
LEFT: L E F T;
RIGHT: R I G H T;
FULL: F U L L;
CROSS: C R O S S;
OUTER: O U T E R;
ON: O N;
WHERE: W H E R E;
GROUP: G R O U P;
BY: B Y;
HAVING: H A V I N G;
ORDER: O R D E R;
LIMIT: L I M I T;
UNION: U N I O N;
ALL: A L L;
DISTINCT: D I S T I N C T;
PARTITION: P A R T I T I O N;
PARTITIONS: P A R T I T I O N S;
STORED: S T O R E D;
ROW: R O W;
FORMAT: F O R M A T;
RANGE: R A N G E;
LESS: L E S S;
THAN: T H A N;

// Additional keywords for full parser
AND: A N D;
OR: O R;
CASE: C A S E;
WHEN: W H E N;
THEN: T H E N;
ELSE: E L S E;
END: E N D;
CAST: C A S T;
VALUES: V A L U E S;
BETWEEN: B E T W E E N;
IN: I N;
IS: I S;
NULL: N U L L;
TRUE: T R U E;
FALSE: F A L S E;
ASC: A S C;
DESC: D E S C;
OFFSET: O F F S E T;
EXCEPT: E X C E P T;
INTERSECT: I N T E R S E C T;
DUPLICATE: D U P L I C A T E;
AGGREGATE: A G G R E G A T E;
UNIQUE: U N I Q U E;
PRIMARY: P R I M A R Y;
KEY: K E Y;
DISTRIBUTED: D I S T R I B U T E D;
HASH: H A S H;
RANDOM: R A N D O M;
BUCKETS: B U C K E T S;
PROPERTIES: P R O P E R T I E S;
REPLACE: R E P L A C E;
ADD: A D D;
OVER: O V E R;
INTERVAL: I N T E R V A L;
LATERAL: L A T E R A L;
DEFAULT: D E F A U L T;
SUM: S U M;
MIN: M I N;
MAX: M A X;

IDENTIFIER: [a-zA-Z_$-￿] [a-zA-Z0-9_$-￿]*;
BACKQUOTED_IDENTIFIER: '`' ('``' | ~'`')* '`';
STRING_LITERAL: '\'' ('\\' . | '\'\'' | ~['\\])* '\'';
DOUBLE_QUOTED_STRING: '"' ('\\' . | '""' | ~["\\])* '"';
NUMBER_LITERAL: [0-9]+ ('.' [0-9]+)?;

DOT: '.';
COMMA: ',';
SEMI: ';';
LPAREN: '(';
RPAREN: ')';
STAR: '*';
EQ: '=';
PLUS: '+';
MINUS: '-';
SLASH: '/';
PERCENT: '%';
LT: '<';
GT: '>';
COLON: ':';
NEQ: '!=' | '<>';
LTE: '<=';
GTE: '>=';
CONCAT: '||';

LINE_COMMENT: '--' ~[\r\n]* -> skip;
BLOCK_COMMENT: '/*' .*? '*/' -> skip;
WS: [ \t\r\n]+ -> skip;
OTHER: .;

fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];
